dataset:
  common:
    NAME: tower                      # 对应 openpoints/dataset/tower.py 中的类名 TowerDataset
    data_root: /root/data/point/data/tower
    split: train
    num_points: 8000
    feat_keys: [xyz, normal, rgb]     # 输入特征组成
    classes: 3                        # 三分类
  train:
    batch_size: 2
    shuffle: True
    augment: True
  val:
    batch_size: 2
    shuffle: False
    augment: False

model:
  NAME: pointnext                     # 确保与你注册的名字一致
  in_channels: 9
  num_classes: 3
  encoder_args:
    in_channels: 9
    width: 64
    depth: 2
    k: 16
    radii: [[0.1], [0.2, 0.4, 0.4, 0.4],
            [0.4, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8],
            [0.8, 1.6, 1.6, 1.6]]
    nsample: [[32], [32, 32, 32, 32],
              [32, 32, 32, 32, 32, 32, 32],
              [32, 32, 32, 32]]
    group_args:
      NAME: ballquery
  decoder_args:
    mlp:
      - [128, 128]
      - [128, 128]
      - [128, 128]
      - [128, 128]

optimizer:
  NAME: AdamW
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  NAME: OneCycleLR
  max_lr: 0.001
  pct_start: 0.1

trainer:
  max_epoch: 60
  val_freq: 1
  log_freq: 10
  save_path: data/pointnext_tower
