dataset:
  common:
    NAME: tower
    data_root: /root/data/point/data/tower

    feat_keys: [xyz, normal, rgb]
    classes: 3
    num_points: 8000
  train:
    split: train
    batch_size: 2
    shuffle: True
    augment: True
  val:
    split: val
    batch_size: 2
    shuffle: False
    augment: False

model:
  NAME: pointnext
  in_channels: 9
  num_classes: 3
  encoder_args:
    NAME: PointNextEncoder
    blocks: [1, 3, 5, 3]
    width: 64
    radius: [[0.1], [0.2, 0.4, 0.4, 0.4], [0.4, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8], [0.8, 1.6, 1.6, 1.6]]
    nsample: [[32], [32, 32, 32, 32], [32, 32, 32, 32, 32, 32, 32], [32, 32, 32, 32]]
    sa_layers: 3
    sa_use_res: True
    expansion: 4
    group_args:
      NAME: ballquery
      normalize_dp: True
  decoder_args:
    NAME: PointNextDecoder
    fp_channels: [64, 64, 64]
  cls_args:
    NAME: SegHead

optimizer:
  NAME: AdamW
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  NAME: OneCycleLR
  max_lr: 0.001
  pct_start: 0.1

trainer:
  max_epoch: 60
  save_path: data/pointnext_tower
  val_freq: 1
  log_freq: 10
